function zspw_keypress
%KEYPRESS   KeyPressFunction for ZSPW.
%   KEYPRESS serves as a KeyPressFunction for the figure generated by ZSPW.
%   The figure vizualizes the ripple selection process.
%       x - show next ripple
%       y - show previous ripple
%       o - reste original view
%
%   See also ZSPW.

% Get application data
H = gcf;
inp = get(gcf,'CurrentCharacter');
x_lim = getappdata(H,'x_lim');
y_lim = getappdata(H,'y_lim');
st = getappdata(H,'st');
nd = getappdata(H,'nd');
sr = getappdata(H,'sr');
rippleindex = getappdata(H,'rippleindex');

% Zoom
switch inp
    case 'o'    % reset original view
        axis([x_lim y_lim])
        rippleindex = 0;
        setappdata(H,'rippleindex',rippleindex)
    case 'x'    % x - next ripple
        rippleindex = rippleindex + 1;
        rippleindex = max(1,rippleindex);
        rippleindex = min(rippleindex,length(st));
        setappdata(H,'rippleindex',rippleindex)
        xlim([st(rippleindex)/sr-0.3 nd(rippleindex)/sr+0.3])
    case 'y'    % y - previous
        rippleindex = rippleindex - 1;
        rippleindex = max(1,rippleindex);
        rippleindex = min(rippleindex,length(st));
        setappdata(H,'rippleindex',rippleindex)
        xlim([st(rippleindex)/sr-0.3 nd(rippleindex)/sr+0.3])
end